apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-session-queuer-deployment
  labels:
    app: selenium-session-queuer
    name: selenium-session-queuer
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queuer
  template:
    metadata:
      labels:
        app: selenium-session-queuer
        name: selenium-session-queuer
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-session-queuer
          image: selenium/session-queuer:4.0.0-beta-1-prerelease-20210106
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5556
              protocol: TCP